### ISSUE TITLE
Error when running generate_secrets

### ISSUE THREAD

**Issue by camba1** [screwdriver-cd/screwdriver-chart#21]
When running generate_secrets.sh ,  the following error occurred:

`sed: 1: "s/{{cookiepassword}}/WG ...": bad flag in substitute command: 'Z'`

Running it a second time, a similar error took place: 

`sed: 1: "s/{{cookiepassword}}/T0 ...": bad flag in substitute command: 'l'`

Eventually it succeeded after running it a few times.

The issue appears to be with the randomly generated `value` which is then used in the sed command:

`sed -i.bak "s/$name/$value/g" screwdriver-api-secrets.yaml`

**Comment by jithine** [comment]
I'm guessing this happens when the random value has  `/` in it

```❯ value=$(cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32 | base64)
❯ echo $value
WWtQ+/1S//JRstRn2ERDUsqyQr7D2lp0R2Qzvvb4vN0=
❯ value=$(cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32 | base64)
❯ echo $value
Q3Iw3EhQenfrcWLxRDYxxuTpd27s2GXZTb7iYmdDxTA=
```
