### ISSUE TITLE
Missing secret when deploying chart causes

### ISSUE THREAD

**Issue by camba1** [screwdriver-cd/screwdriver-chart#22]
When deploying chart, the my-screwdriver-api-XXXX pod fails to instantiate. The following error is thrown:

`Error: couldn't find key jwtqueuesvcpublickey in Secret test-screwdriver/screwdriver-api-secrets`

Looking at the screwdriver-api-secrets.tmpl file, that secret key is not present.

**Comment by pritamstyz4ever** [comment]
This should be fixed now, please try again with new version

**Comment by camba1** [comment]
The new version properly populates the key.
Thanks!
