### ISSUE TITLE
ENOTFOUND test-queue.screwdriver.cd  when trying to run a pipeline

### ISSUE THREAD

**Issue by camba1** [screwdriver-cd/screwdriver-chart#25]
The ingress template of the chart is missing a section for the queue. As such, when the GUI tries to call it, it is unable to find it. 
It probably needs something like 

  - host: test-queue.screwdriver.cd
    http:
      paths:
      - backend:
          service:
            name: my-screwdriver-queue-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific

to match the other ingress rules

<img width="655" alt="Screen Shot 2021-04-30 at 2 47 11 PM" src="https://user-images.githubusercontent.com/7367366/116751105-29382c80-a9c9-11eb-8fea-1ccee8312229.png">

**Comment by pritamstyz4ever** [comment]
Closing, this as you were able to run screwdriver with minikube
