### ISSUE TITLE
GitLab The redirect URI included is not valid.

### ISSUE THREAD

**Issue by ziyi-bear** [screwdriver-cd/screwdriver-chart#28]
we have tried to install screwdriver on self-host kubernetes

chart ans in host
```
....
  hosts:
    api: api.screwdriver.mlc.app
    ui: screwdriver.mlc.app
    store: store.screwdriver.mlc.app
    queue: queue.screwdriver.mlc.app
```

ui: screwdriver.mlc.app is working
![image](https://user-images.githubusercontent.com/54978757/129023030-e71247fc-f3f4-4cc5-a7d8-bfbaae80c27a.png)
and in dev mode has show some error on ui
![image](https://user-images.githubusercontent.com/54978757/129024103-a36a9cdf-0b9d-45b6-a2d7-ecb5813268fa.png)

when press sign in with gitlab will show 
![image](https://user-images.githubusercontent.com/54978757/129023158-f82062f8-868f-44fe-abb5-7b84b56a11d2.png)
```
An error has occurred
The redirect URI included is not valid.
```

example-scm-settings.json
```
{
    "gitlab": {
        "plugin": "gitlab",
        "config": {
            "oauthClientId": "3223fe5f5e77f0f9bebc20783d86f639b491b3df1597dccde356248e18b8a615",
            "oauthClientSecret": "059aad481e22583063db19ae6fb898339eeb409795b0ca1cdeaa65cfdf342338",
            "gitlabHost": "gitlab.gpu.mlc.app",
            "gitlabProtocol": "https",
            "https": true
        }
    }
}
```
GitLab App Setting
![image](https://user-images.githubusercontent.com/54978757/129023856-8ec01b34-b0b8-42ac-bc74-5c0b6f724ef6.png)
https://api.screwdriver.mlc.app/v4/auth/login <- point to api host

 I can't figure out the problem, please help me, thanks

**Comment by jithine** [comment]
@tkyi haven you seen this before ?

**Comment by tkyi** [comment]
Can you try putting the full redirect like this `https://api.screwdriver.mlc.app/v4/auth/login/gitlab:gitlab.com/web`
https://github.com/screwdriver-cd/screwdriver/issues/2016#issuecomment-814473263

**Comment by ziyi-bear** [comment]
GitLab Version (gitlab.gpu.mlc.app)
![image](https://user-images.githubusercontent.com/54978757/129128737-5c241950-358b-4dc4-a1b7-929ef4cd873e.png)
--------------------------------------------------------------------------------------------------
* full redirect set to `https://api.screwdriver.mlc.app/v4/auth/login/gitlab:gitlab.com/web`
![image](https://user-images.githubusercontent.com/54978757/129128825-0a685a91-fb53-4aca-8be4-e9c6703b8553.png)
![image](https://user-images.githubusercontent.com/54978757/129129017-a4791aac-2c74-415f-9b73-2bc593e4a70e.png)
`https://gitlab.gpu.mlc.app/oauth/authorize?client_id=3223fe5f5e77f0f9bebc20783d86f639b491b3df1597dccde356248e18b8a615&response_type=code&redirect_uri=http%3A%2F%2Fapi.screwdriver.mlc.app%2Fv4%2Fauth%2Flogin%2Fgitlab%3Agitlab.gpu.mlc.app%2Fweb&state=8IW5q0zPAPQxTS50Ar12vg`
--------------------------------------------------------------------------------------------------
* full redirect set to `https://api.screwdriver.mlc.app/v4/auth/login/gitlab:gitlab.gpu.mlc.app/web`
![image](https://user-images.githubusercontent.com/54978757/129129161-8a2f342d-47f6-40f4-ad96-6198663595c3.png)
![image](https://user-images.githubusercontent.com/54978757/129129293-6de1c0ae-2bac-479b-ac8f-9add2ba6800a.png)
`https://gitlab.gpu.mlc.app/oauth/authorize?client_id=3223fe5f5e77f0f9bebc20783d86f639b491b3df1597dccde356248e18b8a615&response_type=code&redirect_uri=http%3A%2F%2Fapi.screwdriver.mlc.app%2Fv4%2Fauth%2Flogin%2Fgitlab%3Agitlab.gpu.mlc.app%2Fweb&state=tADFlU2decpUJCPn9G3aPV`

both shows the same error, this gitlab(gitlab.gpu.mlc.app) is for university education, so can create any admin account for you to edit and testing if needed, thanks.

**Comment by ziyi-bear** [comment]
I changed previous suggestions redirect url 

redirect `https://api.screwdriver.mlc.app/v4/auth/login/gitlab:gitlab.gpu.mlc.app/web`
to 
redirect `http://api.screwdriver.mlc.app/v4/auth/login/gitlab:gitlab.gpu.mlc.app/web`

from https to http fix the issue, It's wierd because my gitlab is vaild cert https. Thanks for help, 
![image](https://user-images.githubusercontent.com/54978757/129176248-96dc6335-0aec-464c-a16d-dfa655d12d7f.png)
![image](https://user-images.githubusercontent.com/54978757/129176340-077bbe0a-476f-4a8a-bb78-f783043cbfd1.png)
